name: CI dls-games-api

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 3000
      
    steps:
      - name: Checkout in repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Execute project
        run: node app.js &

      - name: Execute tests
        run: npx cypress run
      
      
      
      

